### ISSUE TITLE
Multiple Issues while starting Docker-Compose 

### ISSUE THREAD

**Issue by machbio** [kbastani/spring-cloud-microservice-example#10]
There are multiple errors that results in Exit Code 1 in Docker-Compose.

Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

MACOS X Yosemite

consul_agent Error

    docker_consul_1 exited with code 1

    consul_1         | 2015-09-03 19:56:14.437 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
    consul_1         | 
    consul_1         | com.ecwid.consul.transport.TransportException: java.net.UnknownHostException: consulagent: unknown error

recommendation_1 Error 

    recommendation_1 | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c8400000, 45613056, 0) failed; error='Cannot allocate memory' (errno=12)

**Comment by machbio** [comment]
Ran into the Same issue on a Ubuntu machine too

Containers: 10
Images: 68
Storage Driver: aufs
 Root Dir: /srv/docker/aufs
 Backing Filesystem: extfs
 Dirs: 88
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-63-generic
Operating System: elementary OS Luna
CPUs: 4
Total Memory: 7.528 GiB


    recommendation_1 | OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f643ed60000, 262144, 0) failed; error='Cannot allocate memory' (errno=12)

**Comment by kbastani** [comment]
Thanks, can you try replacing the docker-compose.yaml file in `spring-boot-microservice-example/docker` with the following? https://gist.github.com/kbastani/ebf403f4a5e1406742df

Also, make sure that when you initialize boot2docker to use the command: `boot2docker init --memory=5000`

This should fix both your issues. Please let me know how it goes.

**Comment by machbio** [comment]
Its working now.

I have no experience with Eureka, but I am not able to understand why the Status field under "Instances currently registered with Eureka"

![screen shot 2015-09-10 at 1 56 41 pm](https://cloud.githubusercontent.com/assets/1488387/9796422/174718ae-57c4-11e5-9b9b-1e4d9b4560d8.png)

Why are the links to the instances not work?

**Comment by kbastani** [comment]
The links to the instances aren't working because the route needs to be added. Those IPs are local and not exposed on the host using Docker.

For the IP only addresses, you can access them by adding the following route:

`$ sudo route add -net 172.17.0.0/16 $(boot2docker ip 2> /dev/null)`
