### ISSUE TITLE
docker-compose.yml file has dead image names

### ISSUE THREAD

**Issue by Kalle80** [kbastani/spring-cloud-microservice-example#25]
Hi, 

could you update the docker-compose.yml file to point to correct images?

```
➜  docker git:(master) docker-compose up -d
Pulling discovery (kbastani/discovery-microservice:latest)...
Pulling repository docker.io/kbastani/discovery-microservice
ERROR: Error: image kbastani/discovery-microservice not found
```

**Comment by jenssaade** [comment]
You can build the docker images locally, just run `mvn install` on the project root. Run `docker-compose up` afterwards from the docker dir.

**Comment by zirconias** [comment]
i have a 8go mbp ,  how we can limit docker resources to be able to launch 4 ou more containers and still work smoothly ?

**Comment by kbastani** [comment]
@zirconias You can try running the example without using Docker, or using AWS EC2
