### ISSUE TITLE
"docker-compose up" command not finished

### ISSUE THREAD

**Issue by mkaratekin** [kbastani/spring-cloud-microservice-example#26]
Hi, I new in Microservice and Docker. When I run "docker-compose up"  command,I would be long time to process and machine'd be slow.  The screen shot here:
![docker](https://cloud.githubusercontent.com/assets/5239421/14123755/c2620aa2-f60a-11e5-9703-88efba75086b.jpg)

**Comment by kbastani** [comment]
Make sure that you have enough memory on your Docker base VM. 

`docker-machine create spring-cloud-microservices --driver=virtualbox --virtualbox-memory=7000 --virtualbox-disk-size=50000`
