### ISSUE TITLE
Commands error

### ISSUE THREAD

**Issue by mkaratekin** [kbastani/spring-cloud-microservice-example#32]
Hi, 
I use Ubuntu 14.04, spring boot 1.3.5, Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_74, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre

When I use this command ;
$ open $(echo \"$(echo $DOCKER_HOST)/movie\"|
            \sed 's/tcp:\/\//http:\/\//g'|
            \sed 's/[0-9]\{4,\}/10000/g'|
            \sed 's/\"//g')

gets me this error:
"Couldn't get a file descriptor referring to the console"

How can i solve this

**Comment by kbastani** [comment]
This command just opens up the movie service in a browser. http://<dockerhost>/movie
