### ISSUE TITLE
Memory usage goes up

### ISSUE THREAD

**Issue by danielbrutti** [kbastani/spring-cloud-microservice-example#34]
Hi,

I cloned the projects and trying to execute it over a linux machine. All containers are created just fine, I can see them with "docker ps" and look at usage with "docker stats".

However, memory keeps going up and up.. eventualy my laptop (core i5, 10gb RAM) stops responding and die!

I tried with mem_limit on each service definition on docker_compose.yml, and I can see the limit working on docker stats... however memory keeps going up and when the container gets > 95% usage it does dead... container stops working and is removed. So.. this setup just prevents my pc to die.. but nothing else.

I also tried with a JHipster project and set JAVA_OPTS for -Xmx and other memory parameters.. but the result is the same.

Can you please help me on this?

Thanks!

**Comment by danielbrutti** [comment]
finally worked with JAVA_OPTS

**Comment by jdiego** [comment]
Hi @danielbrutti, I am with the same problem on my machine. Can you tell me what options do you use in the JAVA_OPTS. 

Thanks
