### ISSUE TITLE
 mvn clean install error

### ISSUE THREAD

**Issue by indie21** [kbastani/spring-cloud-microservice-example#35]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project users-microservice: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by f3rdy** [comment]
The relevant part:

Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused -> [Help 1]

Check that docker is installed properly locally.

**Comment by indie21** [comment]
[INFO] spring-cloud-microservice-example-parent ........... SUCCESS [  0.400 s]
[INFO] users-microservice ................................. FAILURE [  8.599 s]
[INFO] discovery-microservice ............................. SKIPPED
[INFO] api-gateway-microservice ........................... SKIPPED
[INFO] recommendation-microservice ........................ SKIPPED
[INFO] config-microservice ................................ SKIPPED
[INFO] hystrix-dashboard .................................. SKIPPED
[INFO] consul-microservice ................................ SKIPPED
[INFO] movie-microservice ................................. SKIPPED
[INFO] movies-ui .......................................... SKIPPED
[INFO] -----------------------------------------------------------------------


eeeee

**Comment by f3rdy** [comment]
works for me. (see below)

I guess you really need to track down what is blocking your docker daemon on port 2375.

``
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] spring-cloud-microservice-example-parent ........... SUCCESS [  0.590 s]
[INFO] users-microservice ................................. SUCCESS [01:38 min]
[INFO] discovery-microservice ............................. SUCCESS [ 10.106 s]
[INFO] api-gateway-microservice ........................... SUCCESS [  9.484 s]
[INFO] recommendation-microservice ........................ SUCCESS [ 13.512 s]
[INFO] config-microservice ................................ SUCCESS [ 16.555 s]
[INFO] hystrix-dashboard .................................. SUCCESS [  8.300 s]
[INFO] consul-microservice ................................ SUCCESS [  9.838 s]
[INFO] movie-microservice ................................. SUCCESS [ 13.564 s]
[INFO] movies-ui .......................................... SUCCESS [ 49.120 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:10 min
[INFO] Finished at: 2016-07-09T08:58:21+02:00
[INFO] Final Memory: 86M/675M
[INFO] ------------------------------------------------------------------------
```

**Comment by indie21** [comment]
" DOCKER_HOST=unix:///var/run/docker.sock mvn clean install " can solved docker connect problem

**Comment by indie21** [comment]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project users-microservice: Exception caught: Tag 8 not found in repository docker.io/library/java -> [Help 1]

**Comment by f3rdy** [comment]
@indie21 You should be able to do a `docker pull java:8 on your command line. If this won't work, fix your docker setup.

**Comment by indie21** [comment]
[INFO]
[INFO] spring-cloud-microservice-example-parent ........... SUCCESS [  0.523 s]
[INFO] users-microservice ................................. SUCCESS [ 17.703 s]
[INFO] discovery-microservice ............................. SUCCESS [  6.769 s]
[INFO] api-gateway-microservice ........................... SUCCESS [  5.523 s]
[INFO] recommendation-microservice ........................ SUCCESS [ 10.713 s]
[INFO] config-microservice ................................ SUCCESS [  7.072 s]
[INFO] hystrix-dashboard .................................. SUCCESS [  4.855 s]
[INFO] consul-microservice ................................ SUCCESS [10:23 min]
[INFO] movie-microservice ................................. SUCCESS [ 11.012 s]
[INFO] movies-ui .......................................... SUCCESS [13:36 min]
[INFO] ------------------------------------------------------------------------

success finally  , blame to the  great fire wall  of china

**Comment by jasonyang8088** [comment]
I also have the same problem，I fix it just use ”sudo  usermod -aG docker myusername" .

**Comment by JakubBarta** [comment]
@indie21 worked for me, thanks a lot

**Comment by biohazard2u** [comment]
@indie21 cheers

**Comment by joaoduraes** [comment]
This issue happens due to a bug in the docker-maven-plugin from Spotify. Issue linked here - [spotify/docker-maven-plugin issue 218](https://github.com/spotify/docker-maven-plugin/issues/218). 

I had the same issue when running mvn clean install locally in a Mac with Docker for Mac (not the old Docker that required a VM) and solved by updating the ```docker.plugin.version``` to ```0.4.13```.

I can create a merge request if you want. :)

**Comment by alltej** [comment]
I am also getting this error. I checked my docker is installed properly. I am able to run docker commands like `docker run myimage`. I google search the issue and some says I need to setup the environment variable DOCKER_HOSTS. How to verify it's not setup and if not how to set it up? I am running Docker for Windows
