### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by peachli** [kbastani/spring-cloud-microservice-example#36]
What‘s wrong with my install, the error message below shows after i enter "mvn install"
who can help me

```
`[INFO] --- docker-maven-plugin:0.3.258:build (default) @ users-microservice ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Copying /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/target/users-microservice-0.1.0.jar -> /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/target/docker/users-microservice-0.1.0.jar
[INFO] Copying /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/src/main/docker/Dockerfile -> /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/target/docker/Dockerfile
[INFO] Building image kbastani/users-microservice
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] spring-cloud-microservice-example-parent .......... SUCCESS [0.621s]
[INFO] users-microservice ................................ FAILURE [17.831s]
[INFO] discovery-microservice ............................ SKIPPED
[INFO] api-gateway-microservice .......................... SKIPPED
[INFO] recommendation-microservice ....................... SKIPPED
[INFO] config-microservice ............................... SKIPPED
[INFO] hystrix-dashboard ................................. SKIPPED
[INFO] consul-microservice ............................... SKIPPED
[INFO] movie-microservice ................................ SKIPPED
[INFO] movies-ui ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
`
```

**Comment by f3rdy** [comment]
The user microservice has not been build correctly therefore breaking the further process. Please provide the full log output. With that snippet it's impossible to say something.

**Comment by waiterchong** [comment]
give me 1$,I can slove it.



------------------ 原始邮件 ------------------
发件人: "peachli";<notifications@github.com>;
发送时间: 2016年8月25日(星期四) 下午3:23
收件人: "kbastani/spring-cloud-microservice-example"<spring-cloud-microservice-example@noreply.github.com>; 

主题: [kbastani/spring-cloud-microservice-example] install error (#36)




What‘s wrong with my install, the error message below shows after i enter "mvn install"
 who can help me
 
[INFO] --- docker-maven-plugin:0.3.258:build (default) @ users-microservice ---
 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
 SLF4J: Defaulting to no-operation (NOP) logger implementation
 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 [INFO] Copying /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/target/users-microservice-0.1.0.jar -> /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/target/docker/users-microservice-0.1.0.jar
 [INFO] Copying /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/src/main/docker/Dockerfile -> /opt/sping-cloud-demo/spring-cloud-microservice-example/users-microservice/target/docker/Dockerfile
 [INFO] Building image kbastani/users-microservice
 [INFO] ------------------------------------------------------------------------
 [INFO] Reactor Summary:
 [INFO] 
 [INFO] spring-cloud-microservice-example-parent .......... SUCCESS [0.621s]
 [INFO] users-microservice ................................ FAILURE [17.831s]
 [INFO] discovery-microservice ............................ SKIPPED
 [INFO] api-gateway-microservice .......................... SKIPPED
 [INFO] recommendation-microservice ....................... SKIPPED
 [INFO] config-microservice ............................... SKIPPED
 [INFO] hystrix-dashboard ................................. SKIPPED
 [INFO] consul-microservice ............................... SKIPPED
 [INFO] movie-microservice ................................ SKIPPED
 [INFO] movies-ui ......................................... SKIPPED
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------

**Comment by kbastani** [comment]
Closing, since OP didn't respond with full log output.
