### ISSUE TITLE
mvn clean install fails

### ISSUE THREAD

**Issue by sridhar1982** [kbastani/spring-cloud-microservice-example#5]
I followed the instructions from this great blog.
http://www.kennybastani.com/2015/07/spring-cloud-docker-microservices.html

I cloned the git repo and wanted to spin-up docker containers with microservices.

I get the following error upon `mvn clean install`
```
[ERROR] Failed to execute goal on project users-microservice: Could not resolve dependencies for 
project org.kbastani:users-microservice:jar:0.1.0: Failed to collect dependencies at 
org.springframework.data:spring-data-neo4j:jar:3.4.0.RC1 -> org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Failed 
to read artifact descriptor for org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Could not transfer artifact 
org.neo4j:neo4j-cypher-dsl:pom:2.0.1 from/to spring-snapshots (http://repo.spring.io/libs-snapshot-local): 
Failed to transfer file: http://repo.spring.io/libs-snapshot-local/org/neo4j/neo4j-cypher-dsl/2.0.1/neo4j-
cypher-dsl-2.0.1.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]

```

can you help here?

Thanks

**Comment by kbastani** [comment]
In the parent pom.xml file, go ahead and change the repository location to:

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>http://repo.spring.io/libs-snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        ...

I see that there is an issue with the transitive dependency and I will look into it fully first before making the patch. Thanks for the report!

**Comment by sridhar1982** [comment]
this helped. adding this made the build successful
