### ISSUE TITLE
Port clash in microservices

### ISSUE THREAD

**Issue by bas-velthuizen** [kbastani/spring-cloud-microservice-example#8]
Hi,

Great microservice example.

When starting the polyglot persistence demo I noticed a port clash between the movie-microservice and the recommendation-microservice containers, both exposing port 9006
Is this intentional? Or should one f them be moved to 9005?

Kind regards,
Bas Velthuizen

**Comment by bas-velthuizen** [comment]
OK, this had to do with my IDE leaving some directories in existence after changing to the polyglot-persistence branch.
So this was not intentional and not something wrong in the example.

Thanks,
Bas

**Comment by bas-velthuizen** [comment]
Actually, looking at the docker-compose.yml file, the recommendation-service still is mentioned, and on port 9006, the same port as the movie-microservcie. Only the docker image is not being built anymore by maven.

**Comment by kbastani** [comment]
Everything seems to be working now in the master branch. There was an issue with config server not being resolved from some of the other containers. See: https://github.com/kbastani/spring-cloud-microservice-example/commit/9a7d42c3106e58e521a56c70027d9d4dd3f2ea6b
