### ISSUE TITLE
Containers don't start due to unresolved dependency

### ISSUE THREAD

**Issue by oiavorskyi** [kbastani/spring-cloud-microservice-example#9]
I followed the instructions from "Building Microservices with Spring Cloud and Docker" article and at `docker-compose up` stage I see that **consul** container cannot start due to `java.net.UnknownHostException: consulagent`. 

I tried to do `docker-compose up consulagent` first to ensure that it starts before everything else. The issue might be caused by usage of Docker Tools on Mac but I'm not sure if it is the case.

**Comment by kbastani** [comment]
Hi, are you using boot2docker?

**Comment by oiavorskyi** [comment]
It is new Docker Tools distribution that was released as part of 1.8. It replaced boot2docker with docker-machine as a way of running Docker on Mac. Under the hood, I believe, it uses the same boot2docker VirtualBox image.

**Comment by kbastani** [comment]
Please do the following:



Try replacing the `docker-compose.yml` file in `spring-boot-microservice-example/docker` with the following? 

https://gist.github.com/kbastani/ebf403f4a5e1406742df

Also, make sure that when you initialize boot2docker to use the command: `boot2docker init --memory=5000`

This should fix both your issues. Please let me know how it goes.
